[tool.poetry]
name = "learn-detectron"
version = "0.1.0"
description = ""
authors = ["Ming Chen <ming.chen.adam@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
